[package]
name = "gdc_rust_types"
version = "1.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
indexmap = { version = "1.9.3", features = ["serde"] }
openapiv3 = "1.0.3"
serde = { version = "1", features = ["derive"] }
serde-enum-str = "0.4.0"
serde_json = { version = "1", features = ["preserve_order"] }
serde_with = "3"
